services:
  # web:    
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   image: django-k8s:v1
  #   environment:
  #     - PORT=8020
  #   env_file:
  #     - ./web/.env
  #   ports:
  #     - "8001:8020"
  #   depends_on:
  #     - postgres_db
  #   command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh" 
  postgres_db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - web/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis_db:
      image: redis
      restart: always
      expose:
        - 6380
      ports:
        - "6380:6380"
      volumes:
          - redis_data:/data
      entrypoint: redis-server --appendonly yes --port 6380
volumes:
  postgres_data:
  redis_data: